"""Updated

Revision ID: 26178eaffc27
Revises: 7dd3e67c32d1
Create Date: 2020-05-22 22:26:19.686847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26178eaffc27'
down_revision = '7dd3e67c32d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_score_olevel'), 'score', ['olevel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_olevel'), table_name='score')
    # ### end Alembic commands ###
