""" Updated 

Revision ID: 5f11b8436ed8
Revises: f23c57aa93f0
Create Date: 2020-05-22 21:20:41.159152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f11b8436ed8'
down_revision = 'f23c57aa93f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('olevel', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_score_olevel'), 'score', ['olevel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_olevel'), table_name='score')
    op.drop_column('score', 'olevel')
    # ### end Alembic commands ###
