"""Updated

Revision ID: 7dd3e67c32d1
Revises: d1af8802c1b7
Create Date: 2020-05-22 22:23:07.082347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd3e67c32d1'
down_revision = 'd1af8802c1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'olevel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('olevel', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
