"""Updated

Revision ID: d1af8802c1b7
Revises: 5f11b8436ed8
Create Date: 2020-05-22 22:21:27.250464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1af8802c1b7'
down_revision = '5f11b8436ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'olevel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('olevel', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
