"""Updated

Revision ID: e6ae6a83baa0
Revises: 26178eaffc27
Create Date: 2020-05-23 19:25:51.605698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ae6a83baa0'
down_revision = '26178eaffc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_score_olevel'), 'score', ['olevel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_olevel'), table_name='score')
    # ### end Alembic commands ###
